services:
  db:
    image: mysql:latest
    restart: always
    environment: 
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_DATABASE: 'flaskcrud'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - "3306:3306"
    expose:
    #Opnes port  3306 onthe container
     - '3306' 

    volumes: C:\Users\fmalc\OneDrive\Documents\Dev\PYTHON\Rocket_telegram\Banco_mysql

