### Hello World
GET http://127.0.0.1:5000/hello-word


### Login
POST http://127.0.0.1:5000/login
Content-Type: application/json

{
  "username": "felipe",
  "password": "123"
}

###Cadastro de usuário geral 
POST http://127.0.0.1:5000/user
Content-Type: application/json

{
  "username": "marcio",
  "password": "1234"
}


### Logout
GET http://127.0.0.1:5000/logout


### Buscar usuario Cadastrado por ID
GET http://127.0.0.1:5000/user/1


###Rota de atualização de cadastro - UPDATE 
PUT http://127.0.0.1:5000/user/3
Content-Type: application/json

{
  "password": "123"
}

### Deletar usuario 
DELETE http://127.0.0.1:5000/user/1
